# Generated by Django 6.0.2 on 2026-02-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('airport_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('airport_name', models.CharField(db_index=True, max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='city.city')),
            ],
        ),
    ]
