# Generated by Django 4.2.27 on 2026-01-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('airport_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('airport_name', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=30)),
            ],
        ),
    ]
