# Generated by Django 6.0.3 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('time_zone', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_city_country')],
            },
        ),
    ]
