# Generated by Django 6.0.2 on 2026-02-28 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin_class', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('seat_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('occupied', models.BooleanField()),
                ('cabin_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_class.cabinclass')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('flight', 'row_number', 'seat_letter'), name='unique_seat_per_flight_cabin_row_letter')],
            },
        ),
    ]
