# Generated by Django 6.0.2 on 2026-02-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin_class', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=3)),
                ('occupied', models.BooleanField()),
                ('cabin_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_class.cabinclass')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('flight', 'seat_number'), name='unique_seat_per_flight_cabin')],
            },
        ),
    ]
