# Generated by Django 6.0.2 on 2026-02-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cabin_class_name', models.CharField(max_length=100)),
                ('baggage_allowance', models.IntegerField(default=0)),
                ('refundable', models.BooleanField(default=False)),
            ],
        ),
    ]
