# Generated by Django 6.0.3 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=30, unique=True)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
        ),
    ]
