# Generated by Django 6.0.3 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'date_of_birth'), name='unique_passenger_first_last_dob')],
            },
        ),
    ]
