# Generated by Django 6.0.3 on 2026-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='passenger',
            name='unique_passenger_first_last_dob',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
