# Generated by Django 6.0.1 on 2026-01-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_status', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('confirmation_number', models.CharField(db_index=True, max_length=6, unique=True)),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_status.bookingstatus')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
    ]
