# Generated by Django 6.0.3 on 2026-04-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fare_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
