# Generated by Django 6.0.1 on 2026-01-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('is_terminal', models.BooleanField(default=False)),
            ],
        ),
    ]
