# Generated by Django 6.0.3 on 2026-03-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fare', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_fare', to='fare.fare')),
                ('departure_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flight', to='flight.flight')),
                ('return_fare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_fare', to='fare.fare')),
                ('return_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_flight', to='flight.flight')),
            ],
        ),
    ]
