# Generated by Django 6.0.3 on 2026-04-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
