# Generated by Django 6.0.1 on 2026-01-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin_class', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fare_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('cabin_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_class.cabinclass')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('flight', 'cabin_class'), name='unique_fare_per_flight_cabin')],
            },
        ),
    ]
