# Generated by Django 4.2.27 on 2026-01-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('cabin_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fare_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('cabin_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_class.cabinclass')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.UniqueConstraint(fields=('flight', 'cabin_class'), name='unique_fare_per_flight_cabin'),
        ),
    ]
